name: compile
on:
  push:
    branches:
      - main
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download compiler
        uses: actions/download-artifact@v4
        id: download-compiler
        with:
          name: chlasm
          github-token: ${{ secrets.GH_CHL_PAT }}
          repository: Daniels118/blackandwhite
          run-id: 10540693786
      - name: Extract compiler
        run: ls -l ${{steps.download-compiler.outputs.download-path}}
